import { Lead, DailyTask } from "./types";

export const mockLeads: Lead[] = [
  {
    id: "1",
    name: "Ana Paula Silva",
    phone: "(11) 99876-5432",
    origin: "instagram",
    interest: "imovel",
    stage: "followup",
    lastInteraction: "2026-07-01",
    nextAction: {
      description: "Ligar para confirmar interesse na carta de imóvel R$150k",
      dueDate: "2026-07-01",
      channel: "ligacao",
      completed: false,
    },
    notes: "Tem interesse em imóvel no interior. Marido ainda não convencido.",
    createdAt: "2026-06-20",
    value: 150000,
  },
  {
    id: "2",
    name: "Carlos Mendes",
    phone: "(11) 98765-4321",
    origin: "whatsapp",
    interest: "carro",
    stage: "proposta_enviada",
    lastInteraction: "2026-06-27",
    nextAction: {
      description: "Seguir com proposta carro R$60k — prazo acaba amanhã",
      dueDate: "2026-07-01",
      channel: "whatsapp",
      completed: false,
    },
    notes: "Quer carro novo. Enviamos proposta no dia 27.",
    createdAt: "2026-06-18",
    value: 60000,
  },
  {
    id: "3",
    name: "Fernanda Costa",
    phone: "(11) 91234-5678",
    origin: "indicacao",
    interest: "imovel",
    stage: "reuniao_agendada",
    lastInteraction: "2026-07-01",
    nextAction: {
      description: "Reunião às 14h — levar simulação carta R$200k",
      dueDate: "2026-07-01",
      channel: "presencial",
      completed: false,
    },
    notes: "Indicação do João. Quer casa própria até o final do ano.",
    createdAt: "2026-07-01",
    value: 200000,
  },
  {
    id: "4",
    name: "Roberto Alves",
    phone: "(11) 97654-3210",
    origin: "evento",
    interest: "investimento",
    stage: "qualificacao",
    lastInteraction: "2026-07-01",
    nextAction: {
      description: "Enviar material sobre consórcio como investimento",
      dueDate: "2026-07-01",
      channel: "whatsapp",
      completed: false,
    },
    notes: "Empresário. Interessado em diversificar investimentos.",
    createdAt: "2026-06-22",
    value: 300000,
  },
  {
    id: "5",
    name: "Juliana Pereira",
    phone: "(11) 95555-1234",
    origin: "instagram",
    interest: "carro",
    stage: "contato_ativo",
    lastInteraction: "2026-07-01",
    nextAction: {
      description: "Aguardar resposta — sem resposta, ligar amanhã",
      dueDate: "2026-07-01",
      channel: "ligacao",
      completed: false,
    },
    notes: "Curtiu post sobre carro. Mandamos DM hoje.",
    createdAt: "2026-07-01",
    value: 45000,
  },
  {
    id: "6",
    name: "Marcos Souza",
    phone: "(11) 94321-8765",
    origin: "networking",
    interest: "imovel",
    stage: "reuniao_realizada",
    lastInteraction: "2026-06-26",
    nextAction: {
      description: "Enviar proposta formal — reunião foi positiva",
      dueDate: "2026-07-01",
      channel: "whatsapp",
      completed: false,
    },
    notes: "Reunião ótima. Esposa quer ver proposta por escrito.",
    createdAt: "2026-06-15",
    value: 180000,
  },
  {
    id: "7",
    name: "Patricia Lima",
    phone: "(11) 93333-7890",
    origin: "tiktok",
    interest: "carro",
    stage: "prospeccao",
    lastInteraction: "2026-07-01",
    nextAction: {
      description: "Fazer primeiro contato via WhatsApp",
      dueDate: "2026-07-01",
      channel: "whatsapp",
      completed: false,
    },
    notes: "Comentou no TikTok sobre carro dos sonhos.",
    createdAt: "2026-07-01",
    value: 55000,
  },
  {
    id: "8",
    name: "Diego Rodrigues",
    phone: "(11) 92222-6543",
    origin: "instagram",
    interest: "imovel",
    stage: "followup",
    lastInteraction: "2026-07-01",
    nextAction: {
      description: "3º follow-up — última tentativa antes de arquivar",
      dueDate: "2026-07-01",
      channel: "ligacao",
      completed: false,
    },
    notes: "Demonstrou interesse mas sumiu. Tentamos 2x.",
    createdAt: "2026-06-10",
    value: 120000,
  },
  {
    id: "9",
    name: "Camila Ferreira",
    phone: "(11) 91111-2345",
    origin: "whatsapp",
    interest: "investimento",
    stage: "venda",
    lastInteraction: "2026-07-01",
    nextAction: null,
    notes: "VENDA FECHADA! Carta R$100k. Parabéns!",
    createdAt: "2026-06-05",
    value: 100000,
  },
  {
    id: "10",
    name: "Lucas Nascimento",
    phone: "(11) 90000-9876",
    origin: "indicacao",
    interest: "carro",
    stage: "followup",
    lastInteraction: "2026-06-27",
    nextAction: {
      description: "Confirmar se conseguiu aprovação do financiamento",
      dueDate: "2026-07-01",
      channel: "whatsapp",
      completed: false,
    },
    notes: "Esperando aprovação do cônjuge.",
    createdAt: "2026-06-12",
    value: 70000,
  },
];

export const mockTasks: DailyTask[] = [
  {
    id: "t1",
    type: "reuniao",
    leadId: "3",
    leadName: "Fernanda Costa",
    description: "Reunião às 14h — levar simulação carta R$200k",
    dueDate: "2026-07-01",
    completed: false,
    channel: "presencial",
  },
  {
    id: "t2",
    type: "followup",
    leadId: "1",
    leadName: "Ana Paula Silva",
    description: "Ligar para confirmar interesse — carta imóvel R$150k",
    dueDate: "2026-07-01",
    completed: false,
    channel: "ligacao",
  },
  {
    id: "t3",
    type: "proposta",
    leadId: "6",
    leadName: "Marcos Souza",
    description: "Enviar proposta formal para Marcos",
    dueDate: "2026-07-01",
    completed: false,
    channel: "whatsapp",
  },
  {
    id: "t4",
    type: "followup",
    leadId: "2",
    leadName: "Carlos Mendes",
    description: "Follow-up proposta carro — prazo vence hoje",
    dueDate: "2026-07-01",
    completed: false,
    channel: "whatsapp",
  },
  {
    id: "t5",
    type: "contato",
    leadId: "7",
    leadName: "Patricia Lima",
    description: "Primeiro contato — lead do TikTok",
    dueDate: "2026-07-01",
    completed: true,
    channel: "whatsapp",
  },
  {
    id: "t6",
    type: "followup",
    leadId: "8",
    leadName: "Diego Rodrigues",
    description: "3º follow-up — última tentativa",
    dueDate: "2026-07-01",
    completed: false,
    channel: "ligacao",
  },
  {
    id: "t7",
    type: "contato",
    leadId: "5",
    leadName: "Juliana Pereira",
    description: "Ligar — sem resposta no WhatsApp",
    dueDate: "2026-07-01",
    completed: false,
    channel: "ligacao",
  },
  {
    id: "t8",
    type: "followup",
    leadId: "10",
    leadName: "Lucas Nascimento",
    description: "Confirmar aprovação do cônjuge",
    dueDate: "2026-07-01",
    completed: false,
    channel: "whatsapp",
  },
];

export const metricsMock = {
  contacts: { total: 40, done: 22 },
  responses: 14,
  qualifiedConversations: 8,
  meetingsScheduled: 5,
  meetingsDone: 3,
  proposalsSent: 2,
  salesClosed: 1,
  totalRevenue: 100000,
  estimatedCommission: 3000,
  weeklyContacts: [18, 22, 35, 41, 28, 22, 0],
  monthlySales: [2, 3, 1, 4, 2, 1],
};
